openapi: "3.0.0"
info:
  title: sample
  version: "0.1.0"
servers:
  - url: http://localhost/{basePath}
    description: dev server
    variables:
      basePath:
        default: v1
paths:
  $ref: "./paths/index.yaml"
components:
  parameters:
    $ref: "./parameters/index.yaml"
  schemas:
    $ref: "./schemas/index.yaml"
