openapi: "3.0.0"
info:
  title: sample
  version: "0.1.0"
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - $ref: "#/components/parameters/limit"
      responses:
        '200':
          description: A paged array of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Pet"
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - $ref: "#/components/parameters/petId"
      responses:
        '200':
          description: Expected responses to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
  /donuts:
    get:
      summary: List all donuts
      operationId: listDonuts
      tags:
        - donuts
      parameters:
        - $ref: "#/components/parameters/limit"
      responses:
        '200':
          description: A paged array of donuts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Donut"
components:
  parameters:
    petId:
      name: petId
      in: path
      required: true
      description: The id of the pet to retrieve
      schema:
        type: string

    limit:
      name: limit
      in: query
      description: How many items to return at one time (max 100)
      required: false
      schema:
        type: integer
        format: int32
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string

    Donut:
      type: object
      required:
        - flavor
        - id
      properties:
        id:
          type: integer
          format: int64
        flavor:
          type: string
        tag:
          type: string

              
