openapi: "3.0.0"
info:
  title: sample
  version: "0.1.0"
servers:
  - url: http://localhost/{basePath}
    description: dev server
    variables:
      basePath:
        default: v1
paths:
  /pets:
    $ref: "./paths/pets.yaml"
  /pets/{petId}:
    $ref: "./paths/pet.yaml"
  /donuts:
    $ref: "./paths/donuts.yaml"
components:
  parameters:
    petId:
      $ref: "./parameters/petId.yaml"
    limit:
      $ref: "./parameters/limit.yaml"
  schemas:
    Pet:
      $ref: "./schemas/Pet.yaml"
    Donut:
      $ref: "./schemas/Donut.yaml"
